name: Lint Code

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.1'
          extensions: mbstring
          # We add the tools back in globally here
          tools: php-cs-fixer, rector
          coverage: none

      - name: Cache PHP-CS-Fixer
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.os }}-php-cs-fixer-${{ hashFiles('.php-cs-fixer.dist.php') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-php-cs-fixer-${{ hashFiles('.php-cs-fixer.dist.php') }}-
            ${{ runner.os }}-php-cs-fixer-

      - run: mkdir -p /tmp/rector_cache

      - name: Cache Rector
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: /tmp/rector_cache
          key: ${{ runner.os }}-rector-${{ hashFiles('rector.php') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-rector-${{ hashFiles('rector.php') }}-
            ${{ runner.os }}-rector-

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --ansi

      - name: Run Rector
        run: rector process --dry-run --ansi